- id: '1515525794372'
  alias: Felix rum vardag, tänd
  trigger:
  - platform: time
    at: 07:00:00
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: script.turn_on_felix_rum
- id: '180109204500'
  alias: Felix rum vardag, släck
  trigger:
  - platform: time
    at: '22:00:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - service: script.turn_off_felix_rum
- id: '180109204000'
  alias: Felix rum helg, tänd
  trigger:
  - platform: time
    at: 09:30:00
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  action:
  - service: script.turn_on_felix_rum
- id: '180109204700'
  alias: Felix rum helg, släck
  trigger:
  - platform: time
    at: '22:15:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  condition:
  - condition: time
    weekday:
    - fri
    - sat
  action:
  - service: script.turn_off_felix_rum
- id: '1515522028713'
  alias: Felix rum lov, tänd
  trigger:
  - platform: time
    at: 09:30:00
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
  action:
  - service: script.turn_on_felix_rum
- id: '180109203600'
  alias: Felix rum lov, släck
  trigger:
  - platform: time
    at: '22:15:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  action:
  - service: script.turn_off_felix_rum
- id: '1515530983851'
  alias: Allmän belysning, tänd
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: script.turn_on_general_lights
- alias: Morgonbelysning, tänd
  trigger:
  - platform: time
    at: 06:55:00
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: script.turn_on_morning_lights
  id: 0b1073dedfa245b2835600cf6972b74a
- alias: Morgonbelysning, tänd, helg
  trigger:
  - platform: time
    at: 08:30:00
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  action:
  - service: script.turn_on_morning_lights
  id: 9f920a28dc6b4985b53ecb6e13c42a06
- id: '1515530983853'
  alias: Allmän belysning, tänd, helg
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  action:
  - service: script.turn_on_general_lights
- id: '1515530983852'
  alias: Allmän belysning, släck
  trigger:
  - at: '23:45:00'
    platform: time
  - above: '5'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition: 
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: sun
        after: sunrise
      - condition: numeric_state
        entity_id: sensor.yr_cloudiness
        below: '80'      
    - condition: sun
      after: sunset
  action:
  - service: script.turn_off_general_lights
  mode: single
- id: '180109222801'
  alias: Utomhusbelysning, tänd på morgonen
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - condition: sun
    before: sunrise
  action:
  - service: script.turn_on_outdoor
- id: '200305204500'
  alias: Utomhusbelysning, tänd på kvällen
  trigger:
  - event: sunset
    platform: sun
  action:
  - service: script.turn_on_outdoor
- alias: Utomhusbelysning, släck
  id: '180109222803'
  trigger:
  - platform: sun
    event: sunrise
  - platform: time
    at: '23:55:00'
  action:
  - service: script.turn_off_outdoor
- id: '180109231900'
  alias: Telefonladdare på
  trigger:
  - at: '23:00:00'
    platform: time
  - below: '25'
    entity_id: sensor.sm_g960f_battery_level
    platform: numeric_state
  condition:
  - condition: state
    entity_id: person.rickard_nord
    state: home
  action:
  - data: {}
    entity_id: switch.nexa_5
    service: switch.turn_on
  mode: single
- id: '180109231901'
  alias: Telefonladdare av
  trigger:
  - platform: time
    at: 00:00:00
  - platform: time
    at: 07:00:00
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.nexa_5
- id: '190806164100'
  alias: Tänd (mulet)
  trigger:
  - above: '80'
    entity_id: sensor.yr_cloudiness
    for:
      minutes: 10
    platform: numeric_state
  - entity_id: group.my_people
    platform: state
    to: home
  condition:
  - above: 5
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  - condition: state
    entity_id: group.my_people
    state: home
  - above: '80'
    condition: numeric_state
    entity_id: sensor.yr_cloudiness
  action:
  - service: script.turn_on_general_lights
  mode: single
- id: '1603878294613'
  alias: Släck (mulet)
  description: Släck lamporna när det inte är mulet längre
  trigger:
  - platform: state
    entity_id: group.my_people
    for: '5'
    from: home    
    to: not_home
  - platform: numeric_state
    below: '80'
    entity_id: sensor.yr_cloudiness    
  condition:
  - above: 5
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data: {}
    service: script.turn_off_general_lights
  mode: single
- id: '1603895419161'
  alias: Sluta ladda
  description: ''
  trigger:
  - above: '99'
    entity_id: sensor.sm_g960f_battery_level
    for: '5'
    platform: numeric_state
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.nexa_5    
  mode: single
