- id: '1515525794372'
  alias: Felix rum vardag, tänd
  trigger:
  - platform: time
    at: 07:00:00
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: script.turn_on_felix_rum
- id: '180109204500'
  alias: Felix rum vardag, släck
  trigger:
  - platform: time
    at: '22:00:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - service: script.turn_off_felix_rum
- id: '180109204000'
  alias: Felix rum helg, tänd
  trigger:
  - platform: time
    at: 09:30:00
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  action:
  - service: script.turn_on_felix_rum
- id: '180109204700'
  alias: Felix rum helg, släck
  trigger:
  - platform: time
    at: '22:15:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  condition:
  - condition: time
    weekday:
    - fri
    - sat
  action:
  - service: script.turn_off_felix_rum
- id: '1515522028713'
  alias: Felix rum lov, tänd
  trigger:
  - platform: time
    at: 09:30:00
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
  action:
  - service: script.turn_on_felix_rum
- id: '180109203600'
  alias: Felix rum lov, släck
  trigger:
  - platform: time
    at: '22:15:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  action:
  - service: script.turn_off_felix_rum
- id: '1515530983851'
  alias: Allmän belysning, tänd
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: script.turn_on_general_lights
- alias: Morgonbelysning, tänd
  trigger:
  - platform: time
    at: 06:55:00
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: script.turn_on_morning_lights
  id: 0b1073dedfa245b2835600cf6972b74a
- alias: Morgonbelysning, tänd, helg
  trigger:
  - platform: time
    at: 08:30:00
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  action:
  - service: script.turn_on_morning_lights
  id: 9f920a28dc6b4985b53ecb6e13c42a06
- id: '1515530983853'
  alias: Allmän belysning, tänd, helg
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  action:
  - service: script.turn_on_general_lights
- id: '1515530983852'
  alias: Allmän belysning, släck
  trigger:
  - at: '23:45:00'
    platform: time
  - above: '5'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state.attributes.elevation }}'
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: sun
        after: sunrise
      - condition: numeric_state
        entity_id: sensor.yr_cloudiness
        below: '80'
    - condition: sun
      after: sunset
    - condition: state
      entity_id: group.my_people
      state: not_home
  action:
  - service: script.turn_off_general_lights
  mode: single
- id: '180109222801'
  alias: Utomhusbelysning, tänd på morgonen
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - condition: sun
    before: sunrise
  action:
  - service: script.turn_on_outdoor
- id: '200305204500'
  alias: Utomhusbelysning, tänd på kvällen
  trigger:
  - event: sunset
    platform: sun
  action:
  - service: script.turn_on_outdoor
- alias: Utomhusbelysning, släck
  id: '180109222803'
  trigger:
  - platform: sun
    event: sunrise
  - platform: time
    at: '23:55:00'
  action:
  - service: script.turn_off_outdoor
- id: '180109231900'
  alias: Telefonladdare på
  trigger:
  - at: '23:00:00'
    platform: time
  - below: '25'
    entity_id: sensor.sm_g960f_battery_level
    platform: numeric_state
  - platform: time
    at: 06:30:00
  condition:
  - condition: state
    entity_id: person.rickard_nord
    state: home
  action:
  - data: {}
    entity_id: switch.nexa_5
    service: switch.turn_on
  mode: single
- id: '180109231901'
  alias: Telefonladdare av
  trigger:
  - platform: time
    at: 00:00:00
  - platform: time
    at: 07:00:00
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.nexa_5
- id: '190806164100'
  alias: Mulet (tänd)
  trigger:
  - above: '80'
    entity_id: sensor.yr_cloudiness
    for: 0:10:00
    platform: numeric_state
  - entity_id: group.my_people
    platform: state
    to: home
    for: 0:5:00
  - platform: numeric_state
    entity_id: sensor.yr_symbol
    above: '3'
    for: 0:10:00
  - platform: numeric_state
    entity_id: sensor.aktuell_effekt
    for: 0:05:00
    below: '0.2'
  condition:
  - above: '5'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  - condition: state
    entity_id: group.my_people
    state: home
  - condition: numeric_state
    entity_id: sensor.aktuell_effekt
    below: '0.2'
  action:
  - service: script.turn_on_general_lights
  mode: single
- id: '1603878294613'
  alias: Mulet (släck)
  description: Släck lamporna när det inte är mulet längre
  trigger:
  - platform: state
    entity_id: group.my_people
    from: home
    to: not_home
    for: 00:05:00
  - platform: numeric_state
    below: '80'
    entity_id: sensor.yr_cloudiness
    for: 0:10:00
  - platform: numeric_state
    entity_id: sensor.yr_symbol
    below: '4'
    for: 0:10:00
  - platform: numeric_state
    entity_id: sensor.aktuell_effekt
    for: 0:05:00
    above: '0.2'
  condition:
  - above: '5'
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
  action:
  - data: {}
    service: script.turn_off_general_lights
  mode: single
- id: '1603895419161'
  alias: Sluta ladda GS9
  description: ''
  trigger:
  - above: '99'
    entity_id: sensor.sm_g960f_battery_level
    for: '5'
    platform: numeric_state
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.nexa_5
  mode: single
- id: '1610304172777'
  alias: Ladda bilen när det är kallt
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.azarel_charger_sensor
    from: 'Off'
    to: 'On'
  condition:
  - condition: numeric_state
    entity_id: sensor.199_temperature
    below: '10'
  - condition: numeric_state
    entity_id: sensor.azarel_battery_sensor
    below: '20'
  - condition: device
    type: is_off
    device_id: c9c4aa2a0a97e2ca2cc52467b9372ad1
    entity_id: switch.azarel_charger_switch
    domain: switch
  action:
  - type: turn_on
    device_id: c9c4aa2a0a97e2ca2cc52467b9372ad1
    entity_id: switch.azarel_charger_switch
    domain: switch
  mode: single
- id: '1610304940192'
  alias: Laddat till 20%
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.azarel_battery_sensor
    above: '19'
    below: '23'
  condition:
  - condition: state
    entity_id: binary_sensor.azarel_charger_sensor
    attribute: charging_state
    state: Charging
  action:
  - service: notify.mobile_app_sm_g960f
    data:
      title: Teslan har nått 20%
      message: Azarel har laddat tillräckligt för att vara utom fara.
  mode: single
