- id: '1515525794372'
  alias: Felix rum vardag, tänd
  trigger:
  - platform: time
    at: 07:00:00
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: script.turn_on_felix_rum
- id: '180109204500'
  alias: Felix rum vardag, släck
  trigger:
  - platform: time
    at: '22:10:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun
  action:
  - service: script.turn_off_felix_rum
  mode: single
- id: '180109204000'
  alias: Felix rum helg, tänd
  trigger:
  - platform: time
    at: 09:30:00
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: '5'
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  - condition: state
    entity_id: group.my_people
    state: home
  action:
  - service: script.turn_on_felix_rum
- id: '180109204700'
  alias: Felix rum helg, släck
  trigger:
  - platform: time
    at: '23:00:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  condition:
  - condition: time
    weekday:
    - fri
    - sat
  action:
  - service: script.turn_off_felix_rum
  mode: single
- id: '1515522028713'
  alias: Felix rum lov, tänd
  trigger:
  - platform: time
    at: '10:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: '5'
  condition:
  - condition: template
    value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
  action:
  - service: script.turn_on_felix_rum
- id: '180109203600'
  alias: Felix rum lov, släck
  trigger:
  - platform: time
    at: '23:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: '5'
  action:
  - service: script.turn_off_felix_rum
- id: '1515530983851'
  alias: Allmän belysning, tänd
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5
  - platform: state
    entity_id: group.my_people
    from: not_home
    to: home
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: group.my_people
    state: home
  action:
  - service: script.turn_on_general_lights
- id: 9f920a28dc6b4985b53ecb6e13c42a06
  alias: Morgonbelysning, tänd
  trigger:
  - platform: time
    at: 06:55
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: group.my_people
    state: home
  action:
  - service: script.turn_on_morning_lights
- id: 0b1073dedfa245b2835600cf6972b74a
  alias: Morgonbelysning, tänd, helg
  trigger:
  - platform: time
    at: 08:30
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  - condition: state
    entity_id: group.my_people
    state: home
  action:
  - service: script.turn_on_morning_lights
- id: '1515530983853'
  alias: Allmän belysning, tänd, helg
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5
  - platform: state
    entity_id: group.my_people
    from: not_home
    to: home
    for:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < 5 }}'
    - condition: time
      weekday:
      - sat
      - sun
  - condition: state
    entity_id: group.my_people
    state: home
  action:
  - service: script.turn_on_general_lights
- id: '1515530983852'
  alias: Allmän belysning, släck
  trigger:
  - platform: time
    at: '23:45:00'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: '5'
  - platform: state
    entity_id: group.my_people
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: sun
        after: sunrise
      - condition: numeric_state
        entity_id: sensor.yr_cloudiness
        below: '80'
    - condition: sun
      after: sunset
    - condition: state
      entity_id: group.my_people
      state: not_home
  action:
  - service: script.turn_off_general_lights
  mode: single
- id: '180109222801'
  alias: Utomhusbelysning, tänd på morgonen
  trigger:
  - at: 07:00:00
    platform: time
  condition:
  - condition: sun
    before: sunrise
  action:
  - service: script.turn_on_outdoor
- id: '200305204500'
  alias: Utomhusbelysning, tänd på kvällen
  trigger:
  - event: sunset
    platform: sun
  action:
  - service: script.turn_on_outdoor
- id: '180109222803'
  alias: Utomhusbelysning, släck
  trigger:
  - platform: sun
    event: sunrise
  - platform: time
    at: '23:55:00'
  action:
  - service: script.turn_off_outdoor
- id: '180109231900'
  alias: Telefonladdare på
  trigger:
  - platform: time
    at: '23:00:00'
  - platform: numeric_state
    entity_id: sensor.op9_pro_battery_level
    below: 25
  - platform: time
    at: 06:30
  condition:
  - condition: state
    entity_id: person.rickard_nord
    state: home
  - condition: numeric_state
    entity_id: sensor.op9_pro_battery_level
    below: '99'
  action:
  - data: {}
    entity_id: switch.nexa_5
    service: switch.turn_on
  mode: single
- id: '180109231901'
  alias: Telefonladdare av
  trigger:
  - platform: time
    at: 00:00:00
  - platform: time
    at: 07:00:00
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.nexa_5
- id: '190806164100'
  alias: Mulet (tänd)
  trigger:
  - platform: numeric_state
    entity_id: sensor.yr_cloudiness
    above: 80
    for: 00:10:00
  - platform: state
    entity_id: group.my_people
    to: home
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - platform: state
    entity_id:
    - sensor.template_yrwthr
    to: 'True'
  - platform: numeric_state
    entity_id: sensor.template_fronius_solar_power
    below: '0.4'
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    above: 5
    attribute: elevation
  - condition: state
    entity_id: group.my_people
    state: home
  - condition: numeric_state
    entity_id: sensor.template_fronius_solar_power
    below: 0.4
  - condition: state
    entity_id: sensor.template_yrwthr
    state: 'True'
  - condition: numeric_state
    entity_id: sensor.yr_cloudiness
    above: '79'
  action:
  - service: script.turn_on_general_lights
    data: {}
  mode: single
- id: '1603878294613'
  alias: Mulet (släck)
  description: Släck lamporna när det inte är mulet längre
  trigger:
  - platform: state
    entity_id: group.my_people
    from: home
    to: not_home
    for: 00:05:00
  - platform: numeric_state
    entity_id: sensor.yr_cloudiness
    below: 80
    for: 00:10:00
  - platform: state
    entity_id:
    - sensor.template_yrwthr
    to: 'False'
  - platform: numeric_state
    entity_id: sensor.template_fronius_solar_power
    above: '0.5'
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    above: 5
    attribute: elevation
  action:
  - data: {}
    service: script.turn_off_general_lights
  mode: single
- id: '1603895419161'
  alias: Sluta ladda Rickards telefon
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.op9_pro_battery_level
    above: '99'
    for:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  condition:
  - condition: state
    entity_id: person.rickard_nord
    state: home
  action:
  - service: switch.turn_off
    entity_id: switch.nexa_5
  mode: single
- id: '1610304172777'
  alias: Ladda bilen, SoC <20%
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.azarel_charger_sensor
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.azarel_battery_sensor
    below: '20'
  - condition: state
    entity_id: input_boolean.charge_aza
    state: 'off'
  - condition: state
    entity_id: device_tracker.azarel_location_tracker
    state: home
  action:
  - service: automation.turn_on
    entity_id: automation.laddat_till_20
  - service: script.charge_the_tesla
    data: {}
  mode: single
- id: '1610304940192'
  alias: Ladda bilen, stoppa, SoC ≥20%
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.azarel_battery_sensor
    above: '19'
    below: '23'
  condition:
  - condition: state
    entity_id: binary_sensor.azarel_charger_sensor
    attribute: charging_state
    state: Charging
  - condition: state
    entity_id: device_tracker.azarel_location_tracker
    state: home
  - condition: state
    entity_id: input_boolean.charge_aza
    state: 'on'
  action:
  - if:
    - condition: state
      entity_id: binary_sensor.low_price
      state: 'off'
    then:
    - service: script.ladda_tesla_stoppa
      data: {}
    else:
    - service: notify.mobile_app_op9_pro
      data:
        message: Azarel har nått SoC {{ states("sensor.azarel_battery_sensor") }}%
        title: Azarel laddar fortfarande pga. lågt elpris.
  - service: automation.turn_off
    entity_id: automation.laddat_till_20
  mode: single
- id: '1617052336219'
  alias: Dags att ladda plattan
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.sm_p610_batteriniva
    below: '25'
  condition:
  - condition: device
    type: is_not_plugged_in
    device_id: 12560843ff3ebcb9b53643f71e1c6efc
    entity_id: binary_sensor.sm_p610_laddar
    domain: binary_sensor
  action:
  - service: notify.mobile_app_op9pro
    data:
      message: Samsung-plattan har mindre än 25% laddning.
      title: Dags att ladda plattan
  mode: single
- id: '1629725493407'
  alias: Publicera husets ström
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.hem_gen5_electric_consumed_1, sensor.hem_gen5_electric_consumed_2,
      sensor.hem_gen5_electric_consumed_3
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ha/sensor/hem/current/{{trigger.to_state.object_id}}
      payload: '{{trigger.to_state.state}}'
  mode: single
- id: '1633032752936'
  alias: Tänd tidig morgon
  description: ''
  trigger:
  - platform: time
    at: 05:30
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: sun
    before: sunrise
  action:
  - service: script.early_morning_lights_on
    data: {}
  mode: single
- id: '1643056235541'
  alias: Ladda bilen, lågt elpris
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.low_price
    to: 'on'
  - platform: state
    entity_id: binary_sensor.azarel_charger_sensor
    to: 'on'
  condition:
  - condition: state
    entity_id: device_tracker.azarel_location_tracker
    state: home
  - condition: state
    entity_id: binary_sensor.azarel_charger_sensor
    state: 'on'
  - condition: state
    entity_id: binary_sensor.low_price
    state: 'on'
  - condition: state
    entity_id: switch.azarel_charger_switch
    state: 'off'
    enabled: false
  - condition: numeric_state
    entity_id: sensor.azarel_battery_sensor
    above: '19'
    below: '80'
  - condition: state
    entity_id: input_boolean.charge_aza
    state: 'off'
  action:
  - service: script.charge_the_tesla
    data: {}
  mode: single
- id: '1643296123979'
  alias: Ladda bilen, stoppa
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.low_price
    to: 'off'
  condition:
  - condition: state
    entity_id: device_tracker.azarel_location_tracker
    state: home
  - condition: numeric_state
    entity_id: sensor.azarel_battery_sensor
    above: '20'
  - condition: state
    entity_id: binary_sensor.low_price
    state: 'off'
  - condition: state
    entity_id: input_boolean.charge_aza
    state: 'on'
  action:
  - service: script.ladda_tesla_stoppa
    data: {}
  mode: single
- id: '1647968733347'
  alias: Ladda Zoe:n
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  - platform: state
    entity_id:
    - binary_sensor.low_price
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.zoe_battery_level
    below: '95'
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.low_price
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: input_boolean.charge_zoe
    state: 'off'
  action:
  - service: script.ladda_zoe
    data: {}
  mode: single
- id: '1652813052285'
  alias: Wall-E fellarm
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.wall_e
    from: no error
    attribute: error
  - platform: state
    entity_id:
    - vacuum.wall_e
    for:
      hours: 0
      minutes: 30
      seconds: 0
    to: returning
  condition:
  - condition: not
    conditions:
    - condition: state
      state: rain delay
      entity_id: vacuum.wall_e
      attribute: error
  action:
  - service: notify.mobile_app_op9_pro
    data:
      message: Fel på gräsklipparen ({{states("vacuum.wall_e")}}). Batteri {{ state_attr("vacuum.wall_e",
        "battery_level") }}%.
      title: Wall-E larm
  mode: single
- id: '1656709628350'
  alias: Ladda Zoe:n, klocka
  description: ''
  trigger:
  - platform: time
    at: input_datetime.zoe_hour
  condition:
  - condition: state
    entity_id: input_boolean.charge_zoe
    state: 'off'
  action:
  - service: script.ladda_zoe
    data: {}
  mode: single
- id: '1657529930391'
  alias: Morgondagens priser
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.template_nordpool_tomorrow_valid
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_op9_pro
    data:
      message: 'Nu är morgondagens priser uppdaterade.\nPriset, genomsnitt: {{state_attr("sensor.nordpool_kwh_se3_sek_2_10_025",
        "average") | float | round(2) }}, min: {{state_attr("sensor.nordpool_kwh_se3_sek_2_10_025",
        "min") | float | round(2) }}, max: {{state_attr("sensor.nordpool_kwh_se3_sek_2_10_025",
        "max") | float | round(2) }}\n{{ state_attr("sensor.nordpool_kwh_se3_sek_2_10_025","tomorrow")
        }}'
      title: Elpriset uppdaterat
  mode: single
- id: '1657534080615'
  alias: Ladda Zoe:n, stoppa (uppdatera state)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.zoe_charging
    from: 'on'
    to: 'off'
  - platform: state
    entity_id:
    - binary_sensor.zoe_plugged_in
    to: 'off'
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.charge_zoe
  mode: single
- id: '1657535291798'
  alias: Ladda bilen, stoppa (uppdatera state)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.azarel_charger_sensor
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.charge_aza
  mode: single
- id: '1657551301274'
  alias: Ladda Zoe, aktivera klocka
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.zoe_use_clock
    to: 'on'
  condition: []
  action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.ladda_fridas_bil
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.ladda_zoe_pa_tid
  mode: single
- id: '1657551360151'
  alias: Ladda Zoe, deaktivera klocka
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.zoe_use_clock
    to: 'off'
  condition: []
  action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id:
      - automation.ladda_zoe_pa_tid
  - service: automation.turn_on
    data: {}
    target:
      entity_id:
      - automation.ladda_fridas_bil
  mode: single
- id: '1657732972960'
  alias: Ladda Zoe, inkopplad
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.zoe_plugged_in
    to: 'on'
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.zoe_use_clock
      state: 'on'
    then:
    - service: automation.turn_on
      data: {}
      target:
        entity_id: automation.ladda_zoe_pa_tid
    - service: automation.turn_off
      data: {}
      target:
        entity_id: automation.ladda_fridas_bil
    else:
    - service: automation.turn_on
      data: {}
      target:
        entity_id: automation.ladda_fridas_bil
    - service: automation.turn_off
      data: {}
      target:
        entity_id: automation.ladda_zoe_pa_tid
  mode: single
- id: '1657734004303'
  alias: Ladda Zoe, bilen kör
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.zoe_battery_level
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state | int < trigger.from_state.state |
      int }}'
  action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id:
      - automation.ladda_fridas_bil
      - automation.ladda_zoe_pa_tid
  mode: single
