- platform: template
  sensors:
    low_price:
      friendly_name: "Lågt elpris"
      value_template: "{{ state_attr('sensor.nordpool_kwh_se3_sek_3_095_0','low_price') or states('sensor.template_nordpool_current_price')|float <= (states('sensor.elpriset_kr_avg_3')|float*0.7) }}" 
    low_price_off_peak:
      friendly_name: "Lågt elpris (off peak)"
      value_template: "{{ state_attr('sensor.nordpool_kwh_se3_sek_3_095_0','current_price') <= 0.8 and state_attr('sensor.nordpool_kwh_se3_sek_3_095_0','current_price') <= state_attr('sensor.nordpool_kwh_se3_sek_3_095_0', 'off_peak_1') and state_attr('sensor.nordpool_kwh_se3_sek_3_095_0','low_price')}}" 

    yr_wthr:
      friendly_name: "Dåligt väder"
      value_template: >-
        {%set badWeatherList = 'cloudy','fog','heavyrain','heavyrainandthunder','heavyrainshowers','heavyrainshowersandthunder','heavysleet','heavysleetandthunder','heavysleetshowers','heavysleetshowersandthunder','heavysnow','heavysnowandthunder','heavysnowshowers','heavysnowshowersandthunder','lightrain','lightrainandthunder','lightrainshowers','lightrainshowersandthunder','lightsleet','lightsleetandthunder','lightsleetshowers','lightsnow','lightsnowandthunder','lightsnowshowers','lightssleetshowersandthunder','lightssnowshowersandthunder','rain','rainandthunder','rainshowers','rainshowersandthunder','sleet','sleetandthunder','sleetshowers','sleetshowersandthunder','snow','snowandthunder','snowshowers','snowshowersandthunder'%}
        {{states('sensor.yr_symbol') in badWeatherList}}

    bad_weather:
      friendly_name: "Dåligt väder"
      icon_template: >
        {% if is_state('binary_sensor.yr_wthr','on') and states("sensor.yr_cloudiness") | int > 80 and states("sensor.aktuell_effekt") | float(0) < 0.4 %} mdi:weather-cloudy-alert
        {% else %} mdi:weather-partly-cloudy
        {% endif %}
      value_template: >-
        {% if is_state('binary_sensor.yr_wthr','on') and states("sensor.yr_cloudiness") | int > 80 and states("sensor.aktuell_effekt") | float(0) < 0.4 %}
          true
        {% else %}
          false
        {% endif %}

    l2_overcurrent:
      friendly_name: "Överström, L2"
      value_template: >-
        {{ states('sensor.hem_gen5_electric_consumed_2') | float(0) >= 20 and states('sensor.template_spabadet_l2_current_a') | float(0) > 0 }}

    heatpump_ivt_heater:
      friendly_name: "Värmepump IVT, värme"
      value_template: "{{ not (states('switch.varmepumpen_a')|bool) }}"

    heatpump_ivt_hotwater:
      friendly_name: "Värmepump IVT, varmvatten"
      value_template: "{{ not (states('switch.varmepumpen_b')|bool) }}"

    walle_online:
      friendly_name: "Wall-E online"
      value_template: >-
        {{ state_attr('vacuum.wall_e','online') }}

- platform: ping
  host: 192.168.2.29
  name: ChargeNode pie
  scan_interval: 60
