- platform: mqtt
  name: "Shelly1-1"
  state_topic: "shellies/shelly1-68C63AFA72FB/relay/0"
  command_topic: "shellies/shelly1-68C63AFA72FB/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false