# Tellstick Duo temp
- platform: tellstick
  only_named:
  - id: 231
    name: Altan
  - id: 215
    name: Sovrummet
  - id: 199
    name: Kontoret
  - id: 247
    name: Badet
# Weather prediction
- platform: weather_data
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - pressure
    - cloudiness

# iGrill (mini)
- platform: mqtt
  state_topic: "cooking/grill/probe1"
  name: "iGrill Probe 1"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: "cooking/grill/battery"
  name: "iGrill Battery"
  qos: 0
  unit_of_measurement: "%"



### INTEGRATIONS 
- platform: integration
  unique_id: diskmaskinen_kr
  name: Diskmaskinen (kr)
  source: sensor.template_dishwasher_machine_cost
  method: left
  round: 2
  
# - platform: rest
#   resource: "https://dev-app-cn.azurewebsites.net/user/1/car/{{ states("input_number.aza_usercar_id") }}?withLogos=false"
#   method: GET
#   name: "AZA CN status"
#   scan_interval: {{}}


#pushbullet
#  - platform: pushbullet
#    api_key: !secret pushbullet_token

# Samsung printer
#- platform: syncthru
#  resource: http://192.168.1.101

#Nordpool
# - platform: nordpool  
# VAT: True     # Should the prices include vat? Default True
# currency: "SEK"  
# region: "SE3" # What power regions your are interested in.

# - platform: rest
#   resource: http://192.168.2.31/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
#   method: GET
#   name: "Aktuell effekt"
#   value_template: "{{ (value_json.Body.Data.PAC.Value /1000 | float(0))|round(2) }}"
#   unit_of_measurement: 'kW'
#   force_update: true
#   scan_interval: 60
  
# - platform: rest
#   resource: http://192.168.2.31/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
#   method: GET
#   name: "Total energi idag"
#   unit_of_measurement: 'kWh'
#   force_update: true
#   scan_interval: 600
#   value_template: >-
#     {% set tlen = (value_json.Body.Data.DAY_ENERGY.Value|string)|length - 3 %}
#     {{(value_json.Body.Data.DAY_ENERGY.Value/(10**tlen))|round(0) * (10**tlen)/1000}}

#   #"{{ ((value_json.Body.Data.DAY_ENERGY.Value /1000 | float / 10)|round(2)) * 10}}"
