# Tellstick Duo temp
- platform: tellstick
#  only_named:
#  - id: 231
#    name: Altan
#  - id: 215
#    name: Sovrummet
#  - id: 199
#    name: Kontoret
#  - id: 247
#    name: Badet
# Weather prediction
- platform: weather_data
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
    - pressure
    - cloudiness

# iGrill (mini)
# - platform: mqtt
#   state_topic: "cooking/grill/probe1"
#   name: "iGrill Probe 1"
#   qos: 0
#   unit_of_measurement: "°C"
# - platform: mqtt
#   state_topic: "cooking/grill/battery"
#   name: "iGrill Battery"
#   qos: 0
#   unit_of_measurement: "%"
  
- platform: average
  name: 'Elpriset [kr] (avg 3)'
  duration:
    days: 3
  entities:
    - sensor.template_nordpool_current_price

- platform: average
  name: 'Elpriset [kr] (avg)'
  duration:
    days: 1
  entities:
    - sensor.template_elpris_kr

- platform: average
  unique_id: avg_nordpool_24hrs
  name: 'Elpriset [kr] (avg 24h, inkl. moms)'
  duration:
    days: 1
  entities:
    - sensor.template_nordpool_current_price_vat

- platform: average
  unique_id: avg_spabadet_week
  name: 'Spabadet [kWh], veckosnitt'
  duration:
    days: 7
  entities:
    - sensor.spabadet_dag

### INTEGRATIONS 
- platform: integration
  unique_id: diskmaskinen_kr
  name: Diskmaskinen (kr)
  source: sensor.template_dishwasher_machine_cost
  method: left
  round: 2

# - platform: integration
#   unique_id: aza_energy_home_kwh
#   name: "Azarel, energi (kWh)"
#   source: sensor.template_aza_energy_home
#   method: left
#   round: 2

### STATISTICS
- platform: statistics
  unique_id: energy_used_24_hrs
  name: "Energy Used (24 hrs)"
  entity_id: sensor.template_house_net_energy_kwh
  state_characteristic: change
  max_age:
    hours: 24
  sampling_size: 1440

- platform: statistics
  unique_id: energycost_24hrs
  name: "Energy × Cost (24 hrs)"
  entity_id: sensor.house_cost_real
  state_characteristic: change
  max_age:
    hours: 24
  sampling_size: 1440

# - platform: rest
#   resource: "https://dev-app-cn.azurewebsites.net/user/1/car/{{ states("input_number.aza_usercar_id") }}?withLogos=false"
#   method: GET
#   name: "AZA CN status"
#   scan_interval: {{}}


# - platform: rest
#   resource: http://192.168.2.31/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
#   method: GET
#   name: "Aktuell effekt"
#   value_template: "{{ (value_json.Body.Data.PAC.Value /1000 | float(0))|round(2) }}"
#   unit_of_measurement: 'kW'
#   force_update: true
#   scan_interval: 60
  
# - platform: rest
#   resource: http://192.168.2.31/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
#   method: GET
#   name: "Total energi idag"
#   unit_of_measurement: 'kWh'
#   force_update: true
#   scan_interval: 600
#   value_template: >-
#     {% set tlen = (value_json.Body.Data.DAY_ENERGY.Value|string)|length - 3 %}
#     {{(value_json.Body.Data.DAY_ENERGY.Value/(10**tlen))|round(0) * (10**tlen)/1000}}

#   #"{{ ((value_json.Body.Data.DAY_ENERGY.Value /1000 | float / 10)|round(2)) * 10}}"
