sensor:
  - name: "iGrill Probe 1"
    unique_id: "igrill_temperature"
    state_topic: "cooking/grill/probe1"
    qos: 0
    unit_of_measurement: "°C"
  - name: "iGrill Battery"
    unique_id: "igrill_battery"
    state_topic: "cooking/grill/battery"
    qos: 0
    unit_of_measurement: "%"

light:
  - name: "Utebaren mqtt"
    unique_id: "utebaren"
    payload_on: "on"
    payload_off: "off"
    qos: 1
    state_topic: "shellies/shelly1-68C63AFA72FB/relay/0"
    command_topic: "shellies/shelly1-68C63AFA72FB/relay/0/command"
    json_attributes_topic: "shellies/shelly1-68C63AFA72FB/info"
    retain: false

# - platform: mqtt
#   name: "Shelly1PM-example"
#   unique_id: "shelly_1pm_example"
#   payload_on: "on"
#   payload_off: "off"
#   qos: 1
#   state_topic: "shellies/shelly1pm-xxxxxxx/relay/0"
#   command_topic: "shellies/shelly1pm-xxxxxxx/relay/0/command"
#   json_attributes_topic: "shellies/shelly1pm-xxxxxxx/info"

# shellies/shelly1pm-485519CB0B57/relay/0